persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Standard MQTT Port
listener 1883
allow_anonymous true

# Websockets Port (For the Browser/Frontend)
listener 9001
protocol websockets
allow_anonymous true
