# Global Agent Configuration
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

# MQTT Input Plugin
[[inputs.mqtt_consumer]]
  servers = ["tcp://myems-mqtt-broker:1883"]
  topics = [
    "data/dev/#",
  ]
  username = "th-testing-2w"
  password = "Aa12345678@@"
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    [[inputs.mqtt_consumer.json_v2.object]]
      path = "reported"
      included_keys = ["*"]
      # Esto aplanará 0_1_1, 0_1_2 etc como tags o campos
      disable_prepend_keys = true

# InfluxDB v2 Output Plugin
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
