version: '3.8'
services:
  api:
    build: ../myems-api
    command: gunicorn app:api -b 0.0.0.0:8000 --timeout 600 --workers=4
    volumes:
      - c:\myems-upload:/var/www/myems-admin/upload
    restart: always
    ports:
      - "8000:8000"

  aggregation:
    build: ../myems-aggregation
    command: python main.py
    restart: always

  cleaning:
    build: ../myems-cleaning
    command: python main.py
    restart: always

  modbus_tcp:
    build: ../myems-modbus-tcp
    command: python main.py
    restart: always

  normalization:
    build: ../myems-normalization
    command: python main.py
    restart: always

  admin:
    build: ../myems-admin
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    healthcheck:
      test: [ "CMD","nginx","-t" ]
    volumes:
      - c:\myems-upload:/var/www/myems-admin/upload
    restart: always
    ports:
      - "8001:8001"
  web:
    build: ../myems-web
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    healthcheck:
      test: [ "CMD","nginx","-t" ]
    restart: always
    ports:
      - "80:80"

  broker:
    build: ../myems-mqtt-broker
    container_name: myems-mqtt-broker
    env_file:
      - ../myems-mqtt/.env
    environment:
      - MQTT_USER=${MYEMS_MQTT_BROKER_USERNAME}
      - MQTT_PASSWORD=${MYEMS_MQTT_BROKER_PASSWORD}
    volumes:
      - ../myems-mqtt-broker/config:/mosquitto/config
      - ../myems-mqtt-broker/data:/mosquitto/data
      - ../myems-mqtt-broker/log:/mosquitto/log
    ports:
      - "1883:1883"
    restart: always

  myems_mqtt:
    build: ../myems-mqtt
    command: python main.py
    restart: always
    depends_on:
      - broker