persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# MQTT Non-encrypted
listener 1883
protocol mqtt

# WebSocket Listener (para el navegador)
listener 9001
protocol websockets

# Setup authentication
password_file /mosquitto/config/passwd
allow_anonymous false

# (Optional) Reserve 8883 if you want both, but for now we stick to requested 1883
# listener 8883
# cafile /mosquitto/config/certs/ca.crt
# certfile /mosquitto/config/certs/server.crt
# keyfile /mosquitto/config/certs/server.key
