persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# MQTT over TLS
listener 8883
protocol mqtt

# Setup authentication
password_file /mosquitto/config/passwd
allow_anonymous false

# TLS Configuration
cafile /mosquitto/config/certs/ca.crt
certfile /mosquitto/config/certs/server.crt
keyfile /mosquitto/config/certs/server.key
tls_version tlsv1.2
